### ISSUE TITLE
Doesn't seems to work with Svelte REPL

### ISSUE THREAD

**Issue by Tal500** [benmccann/esm-env#1]
Reproduction: https://svelte.dev/repl/1e96cbd4bcd148e3b85a4c8ca76d7309?version=3.48.0

More details: https://github.com/orefalo/svelte-splitpanes/pull/39#issuecomment-1347089124

My guess is that REPL doesn't respect the `exports` field in `package.json`.

**Comment by Tal500** [comment]
A cleaner reproduction: https://svelte.dev/repl/58ae14b7f112454aa83125b767f9a62a?version=3.54.0

**Comment by Conduitry** [comment]
IIRC, yes, the Svelte REPL does not respect the `exports` field. (I think there's an issue for it somewhere.) I'm not sure there's anything for this library to do about that though.

**Comment by Tal500** [comment]
> IIRC, yes, the Svelte REPL does not respect the `exports` field. (I think there's an issue for it somewhere.) I'm not sure there's anything for this library to do about that though.

Well, the library can always have a "fallback" mode, by having a `index.js` file containing:
```js
export const BROWSER = typeof window !== 'undefined';
export const DEV = false;
```

This will be loaded for environments that doesn't support the `exports` field.

BTW: Wonder why minificators (e.g. terser) doesn't like to optimize the 'typeof browser' in compile time. Any idea to people here?

**Comment by Tal500** [comment]
> IIRC, yes, the Svelte REPL does not respect the `exports` field. (I think there's an issue for it somewhere.) I'm not sure there's anything for this library to do about that though.

Will the Svelte team prioritize this issue? The main point of this library in the SvelteKit point of view, as far as I know, is to solve the problem I mentioned in https://github.com/sveltejs/kit/issues/5879.

For reference, the issue of Svelte REPL for the `exports` field support: https://github.com/sveltejs/sites/issues/134

**Comment by Tal500** [comment]
> > IIRC, yes, the Svelte REPL does not respect the `exports` field. (I think there's an issue for it somewhere.) I'm not sure there's anything for this library to do about that though.
> 
> Well, the library can always have a "fallback" mode, by having a `index.js` file containing:
> 
> ```js
> export const BROWSER = typeof window !== 'undefined';
> export const DEV = false;
> ```

In the case this project wouldn't like to change its code here, I did it by myself by creating a new package [esm-env-robust](https://github.com/Tal500/esm-env-robust).
The [demo on Svelte REPL](https://svelte.dev/repl/6ae4871d6a48460fb8be28afaf9a6e1d?version=3.54.0) seems to work with this package.

**Comment by benmccann** [comment]
@Tal500 that sounds like a reasonable suggestion. Would you like to send a PR for it?

**Comment by Tal500** [comment]
> @Tal500 that sounds like a reasonable suggestion. Would you like to send a PR for it?

@benmccann I can send PR.
I wonder though - do you agree with me that on this fallback, we should set `export const DEV = false`?

Edit:
Done in #2

**Comment by benmccann** [comment]
will be fixed by https://github.com/sveltejs/sites/pull/445
