### ISSUE TITLE
How to import non-production without a bundler?

### ISSUE THREAD

**Issue by Glench** [benmccann/esm-env#3]
Hey! I have a sveltekit project with a `$lib/db` and I want to access that library outside the context of sveltekit because I have scripts I need to run. I import `esm-env` in that library and use `DEV`. However, in my testing (running a script that imports `lib/db` with node-ts), `DEV` is always false and it looks like it's pulling in prod-ssr, even though my `NODE_ENV=development`. Any ideas about how I can import the correct version of esm-env to match my environment?

**Comment by benmccann** [comment]
https://nodejs.org/api/cli.html#-c-condition---conditionscondition

**Comment by Glench** [comment]
Thanks!
