### ISSUE TITLE
Seemingly different eval on two enviornments

### ISSUE THREAD

**Issue by GanizaniSitara** [benmccann/esm-env#4]
Hi Ben,

may I ask for a pointer - I've come here from https://github.com/open-webui/open-webui/discussions/931 where "import  { BROWSER }  from 'esm-env'; " seems to evaluate to false on my work machine, works with ostensibly the same config at home and isn't problem for anyone else using open-webui. I'm not a JS dev and wanted to pick your brain for any pointers? Many thanks in advance. GS

**Comment by benmccann** [comment]
There's not really enough info here to be able to provide help. If you're using SvelteKit/Vite it should set the variable appropriately. This package uses Node.js conditions to set the variable: https://nodejs.org/api/packages.html#community-conditions-definitions. Perhaps you're somehow running it with different conditions than what Vite does out-of-the-box?
